### ISSUE TITLE
Onboarding flow, dashboard layout improvements, etc. - guide users to the right places

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#1436]
To Do
- [ ] Onboarding walk through in sheet
- [x] Code editor quick snippets #1656
- [x] Dashboard onboarding banner #1676
- [x] Rename Team files and Private Files #1676
- [x] "New file" dialog for creating files in a variety of ways #1676
- [x] Connections work (exploring schema from dashboard, start a new file with query to table) #1676
- [x] AI chat placeholder with suggestions?

Other
- [ ] Collect company name.
- [ ] Make video intro obvious.
- [ ] Add help menu with video tutorials
- [ ] Make it easier to leave feedback and ask for help
- [ ] Encourage signup with business email?

Figma https://www.figma.com/design/s16tV68uqczPv0lPDmlEjq/Onboarding-Flow-Improvements?node-id=0-1&t=d0E9WfYyHWxgPdW9-1

**Comment by luke-quadratic** [comment]
Closed - should re-open when we want to do more scoped work on onboarding
