### ISSUE TITLE
Keyboard shortcut tracking/implementation list 

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#1536]
Prioritizing essential keyboard shortcuts from mainstream spreadsheets that aren't yet supported in Quadratic. 

**Please leave a comment** if you want a specific shortcut prioritized.  

- [ ] F2: edit cell 
- [ ] Ctrl+page-up/ctrl+page-down: go to next/prior sheet: 
- [ ] Ctrl + d: fill down from the cell above
- [ ] Ctrl + r: fill right from the cell to the left
- [ ] Shift+space: select row
- [ ] Shift+space: select column 
- [ ] Ctrl+5: strikethrough 
- [ ] Ctrl + `: show formulas in cells instead of results

**Comment by AyushAgrawal-A2** [comment]
@luke-quadratic 
> [ ] Ctrl+page-up/ctrl+page-down: go to next/prior sheet:
Ctrl+page-up/ctrl+page-down  - this combination does not fire an event on chrome (not sure about other browsers). It is reserved for browser tab change.

**Comment by davidkircos** [comment]
I think we should implement shortcuts as part of a JSON "Theme" so users can customize it later. The ability to customize it doesn't need to be in the first iteration here, but building a framework for referencing shortcuts from a JSON definition would ba great foundation before adding a bunch more shortcuts.

**Comment by luke-quadratic** [comment]
That makes sense - expanded the scope of the issue. 

@AyushAgrawal-A2 edited original issue for a JSON theme that users can edit plus changed the button presses for switching sheets (note that there are 3 possible ways in update)

**Comment by luke-quadratic** [comment]
Ctrl + ` covered in another issue #2231 

If we want to prioritize a shortcut JSON it should be a sep issue
