### ISSUE TITLE
AI Chat: Small Fixes

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#2077]
- [x] Open AI chat by default for every file. Once user has closed and opened AI chat with sidebar 3 times, AI Chat open by default only on files with <=1 transaction (so file imports still see it). @jimniels #2090 
- [x] Focus grid on new file load, not chat. @AyushAgrawal-A2 #2090  
- [x] Move the chat history button to the center button, with the new chat on the left. Make new more obvious. Blue? @jimniels #2090 
- [ ] Fix with AI on the sheet hover hover should prompt left chat instead of right chat. Keep the Fix with AI button in the code editor opening in the code editor chat. Wait for A1.
- [x] While a chat response is running, the user can "send" another chat. But it just disappears. This should be prevented until the previous chat finishes. #2090 
- [x] Cmd + K to open chat #2090 
- [x] AI Chat often tries to say the answer that it has returned to the sheet, but the answer in the sheet is correct and in the AI chat it is wrong; AI chat can try to explain but it shouldn't try to also say the answer. #2090
- [x] Prompt AI to not answer questions in the chat, answer in the sheet. Often gives one answer on the sheet and one in the chat that are different. The one on the sheet is correct and the one in the chat is incorrect. #2090
- [x] Prompt AI to not use a conditional return. Quadratic does not support conditional returns. #2090
- [ ] Not AI: Code editor show collapsed by default instead of expanded.
- [x] Show actual API error to user, instead of a generic status 400. #2090
- [ ] Show Console as context in Code Editor Chat
- [ ] AI responses don't scale with text size changes in editor 

Needs scope
- [x] Make the initial state a little more "What can I help with?". @jimniels #2090
- [x] Apply flow in Chat for Code Editor is wonky. Proposal: Separating Apply and Run? @jimniels #2086 
- [x] Apply button in right chat should show up as disabled while loading code. Possibly collapse code by default and apply just shows it above? @jimniels #2086
- [x] Move thumbs up and thumbs down to be more obvious, and don't hide run button. @jimniels #2086

**Comment by luke-quadratic** [comment]
Vast majority fixed - ones that are not fixed will be opened as scoped independent single issues.
